import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";
import "nes.css/css/nes.min.css";
import Navbar from "@/components/Navbar/Navbar";

const pressStart2P = Press_Start_2P({ weight: "400", subsets: ["latin"] })


export const metadata: Metadata = {
  title: "Copcrush 2025 Ver",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={pressStart2P.className}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
